"""Add notes field to leads

Revision ID: 0e9ab2ae180c
Revises: 5341816bfa5c
Create Date: 2026-01-09 20:22:58.509002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e9ab2ae180c'
down_revision: Union[str, None] = '5341816bfa5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'notes')
    # ### end Alembic commands ###
